name: Check and upload images

on:
  push:
    branches:
      - main

jobs:
  check_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check and upload images
        env:
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_ACCOUNT_KEY: ${{ secrets.B2_ACCOUNT_KEY }}
          B2_BUCKET_NAME: brandbuzza
        run: deno run verify-csv.ts
