name: Check and upload images

on:
  push:
    branches:
      - main
    paths:
      - 'data/brands.csv'

jobs:
  check_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Check and upload images
        env:
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_ACCOUNT_KEY: ${{ secrets.B2_ACCOUNT_KEY }}
          B2_BUCKET_NAME: brandbuzza
        run: node verify-and-process-csv.js
