name: Check and upload images

on:
  push:
    branches:
      - main
    paths:
      - 'data/brands.csv'

jobs:
  check_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Install dependencies
        run: npm install
      - name: Check and upload images
        env:
          B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
          B2_APP_ID: ${{ secrets.B2_APP_ID }}
          B2_BUCKET_ID: ${{ secrets.B2_BUCKET_ID }}
          B2_BUCKET_NAME: brandbuzza
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          touch .env
          echo B2_APP_KEY=$B2_APP_KEY >> .env
          echo B2_APP_ID=$B2_APP_ID >> .env
          echo B2_BUCKET_ID=$B2_BUCKET_ID >> .env
          echo B2_BUCKET_NAME=$B2_BUCKET_NAME >> .env
          echo GITHUB_TOKEN=$GITHUB_TOKEN >> .env
          echo GITHUB_ACTOR=$GITHUB_ACTOR >> .env
          node verify-and-process-csv.js
